name: test-metrics-5m
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start a kind cluster with containerd
        uses: helm/kind-action@v1.11.0
        with:
          cluster_name: kind-${{ github.run_id }}
          kubectl_version: "v1.25.2"
          config: ./hack/ci/containerd-cluster-conf.yaml
      - name: Build image
        run: ./hack/ci/build.sh
      - name: Set image version
        run: |
          echo "VALUE_FILE=charts/warm-metal-csi-driver/values.yaml" >> "$GITHUB_ENV"
          echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"
          echo "HELM_NAME=wm-csi-integration-tests" >> "$GITHUB_ENV"
      - name: Install the CSI Driver
        run: |
          trap "kubectl -n kube-system describe po" ERR
          helm install ${HELM_NAME} charts/warm-metal-csi-driver -n kube-system \
            -f ${VALUE_FILE} \
            --set csiPlugin.image.tag=${IMAGE_TAG} \
            --wait \
            --debug
      - name: Test metrics
        run: ./test/integration/test-metrics.sh
      - name: Uninstall the CSI Driver
        run: helm uninstall -n kube-system ${HELM_NAME} --wait
