name: restart-ds-crio-8mins
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start a kind cluster with crio
        uses: helm/kind-action@v1.4.0
        with:
          cluster_name: kind-${{ github.run_id }}
          kubectl_version: "v1.25.2"
          node_image: "docker.io/warmmetal/kindest-node-crio:v1.25.2-csi-driver-image"
      - name: Build image
        run: ./hack/ci/build.sh
      - name: Set image version
        run: |
          echo "VALUE_FILE=charts/warm-metal-csi-driver/values-crio.yaml" >> "$GITHUB_ENV"
          echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"
          echo "HELM_NAME=wm-csi-integration-tests" >> "$GITHUB_ENV"
      - name: Install the CSI Driver
        run: |
          helm install ${HELM_NAME} charts/warm-metal-csi-driver -n kube-system \
            -f ${VALUE_FILE} \
            --set csiPlugin.image.tag=${IMAGE_TAG} \
            --wait
      - name: Test volumes between the ds restarted
        run: ./test/integration/restart-ds.sh
      - name: Uninstall the CSI Driver
        run: helm uninstall -n kube-system ${HELM_NAME} --wait
